# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:16.04

RUN apt update && \
    apt install -y \
        automake \
        build-essential \
        clang \
        cmake \
        curl \
        doxygen \
        gawk \
        git \
        gcc \
        golang \
        g++ \
        libssl-dev \
        libtool \
        make \
        ninja-build \
        pkg-config \
        python-pip \
        shellcheck \
        tar \
        unzip \
        wget \
        zlib1g-dev

WORKDIR /var/tmp/Downloads
RUN wget -q https://github.com/c-ares/c-ares/archive/cares-1_15_0.tar.gz && \
    tar -xf cares-1_15_0.tar.gz && \
    cd /var/tmp/Downloads/c-ares-cares-1_15_0 && \
    ./buildconf && ./configure && make -j $(nproc) && \
    make install && \
    ldconfig

# Install grpc from source
WORKDIR /var/tmp/ci
COPY install-grpc.sh /var/tmp/ci
RUN /var/tmp/ci/install-grpc.sh
